"""Map explorer basemap generators — water + secondary highways (origin-shifted EPSG:3401).

Both layers originate from OpenStreetMap via the Overpass API. The *original* OSM
fetch is a network call that requires a descriptive User-Agent header (Overpass
etiquette); these generators do NOT re-fetch — they read cached Overpass exports
(inline-geometry JSON) off disk and reproject/clip/simplify them. To refresh the
raw OSM cache you must re-run the upstream Overpass query with network access.

Output: viewer/static/mapdata/  (served at /mapdata/). Regenerate with:
    python analysis/scripts/build_explorer_basemap.py

Raw OSM cache locations consumed here:
  - water:     C:\\tmp\\osm_water_rivers.json   (Overpass natural=water/riverbank)
               C:\\tmp\\ne_lakes.geojson, C:\\tmp\\ne_lakes_na.geojson  (Natural Earth NE lakes)
  - secondary: data/osm/alberta_osm_highways.json  (in-repo Overpass highways export;
               same source as trunk.json/highways.json — filtered to highway=secondary)

Note: province.json, trunk.json, and highways.json are NOT produced here — they are
relocated as-is and regenerated by other (out-of-scope) generators. build_water()
depends on province.json already existing in OUT (the province silhouette clip).
"""
import json, time
from pathlib import Path
import geopandas as gpd
import pandas as pd
from shapely.geometry import Polygon, LineString
from shapely.ops import polygonize, unary_union

REPO = Path(r"C:\Users\email\Documents\Claude\Projects\Electoral Boundary Analysis\alberta_audit")
OUT = REPO / "viewer" / "static" / "mapdata"
TMP = Path(r"C:\tmp")


def build_water():
    """water.json v2 — OSM river BANK polygons (so edges sit on shoreline ED lines) + NE lakes.

    Rivers: OSM natural=water/water=river + waterway=riverbank (ways + multipolygon relations),
    assembled into polygons. These are real banks, not centerlines, so where an ED boundary follows
    a river the water edge lands on it. Lakes: the few largest NE lakes (unchanged).
    Output: [{"path":[ring], "kind":"river"|"lake"}] — all FILLED polygons in shifted EPSG:3401.
    """
    SIMP = 8.0   # metres — keep banks crisp (they must align with ED lines), just drop redundant verts
    t0 = time.time()
    meta = json.loads((REPO / "docs" / "data" / "map_meta.json").read_text())
    ox, oy = meta["origin_x"], meta["origin_y"]
    prov_raw = json.loads((OUT / "province.json").read_text())
    province = unary_union([Polygon(p[0]) for p in prov_raw if p and len(p[0]) >= 4]).buffer(300)

    # ── OSM river polygons ──
    osm = json.loads((TMP / "osm_water_rivers.json").read_text(encoding="utf-8"))
    polys, loose = [], []
    for e in osm["elements"]:
        if e["type"] == "way" and e.get("geometry"):
            c = [(p["lon"], p["lat"]) for p in e["geometry"]]
            if len(c) >= 4 and c[0] == c[-1]:
                polys.append(Polygon(c))
            elif len(c) >= 2:
                loose.append(LineString(c))
        elif e["type"] == "relation":
            for m in e.get("members", []):
                if m.get("role") in ("outer", "") and m.get("geometry"):
                    c = [(p["lon"], p["lat"]) for p in m["geometry"]]
                    if len(c) >= 2:
                        loose.append(LineString(c))
    if loose:
        polys += [g for g in polygonize(unary_union(loose))]
    print(f"OSM river polygons: {len(polys)}  {time.time()-t0:.0f}s")

    gs = gpd.GeoSeries(polys, crs=4326).to_crs(3401).translate(xoff=-ox, yoff=-oy).buffer(0).simplify(SIMP)
    gs = gs[gs.is_valid & ~gs.is_empty]
    gs = gs[gs.intersects(province)].intersection(province)
    gs = gs[~gs.is_empty]

    out = []
    def emit(geom, kind):
        gt = geom.geom_type
        if gt == "Polygon":
            if geom.area < 2000:   # drop slivers (<0.002 km^2)
                return
            out.append({"path": [[round(x, 1), round(y, 1)] for x, y in geom.exterior.coords], "kind": kind})
        elif gt in ("MultiPolygon", "GeometryCollection"):
            for g in geom.geoms:
                emit(g, kind)
    for geom in gs:
        emit(geom, "river")
    nr = len(out)

    # ── NE lakes: 3 largest, filled (unchanged) ──
    def load_ne_lakes():
        parts = []
        for f in ("ne_lakes.geojson", "ne_lakes_na.geojson"):
            p = TMP / f
            if p.exists():
                g = gpd.read_file(p)[["geometry"]]
                g = g[~g.geometry.is_empty & g.geometry.notna()]
                parts.append(g.to_crs(3401))
        g = gpd.GeoDataFrame(pd.concat(parts, ignore_index=True), geometry="geometry", crs=3401)
        g["geometry"] = g.geometry.translate(xoff=-ox, yoff=-oy)
        g = g[g.intersects(province)]
        g["geometry"] = g.geometry.intersection(province)
        return [geom for geom in g.geometry if not geom.is_empty]

    for geom in sorted(load_ne_lakes(), key=lambda g: g.area, reverse=True)[:3]:
        emit(geom, "lake")
    nl = len(out) - nr

    (OUT / "water.json").write_text(json.dumps(out, separators=(",", ":")))
    sz = (OUT / "water.json").stat().st_size
    verts = sum(len(d["path"]) for d in out)
    print(f"water.json: {nr} river polys + {nl} lake polys = {len(out)} ({verts} verts, {sz/1e6:.2f}MB)  {time.time()-t0:.0f}s")


def build_secondary():
    """Extract OSM secondary highways -> secondary.json (origin-shifted 3401).

    Same source as trunk.json (data/osm/alberta_osm_highways.json, Overpass export with inline
    geometry). Output mirrors trunk.json: [{"path":[[x,y],...]}]. Simplified to keep the file
    light, clipped to the province.
    """
    SIMP = 90.0   # metres — trunk is heavily simplified (~6 verts/path); match that weight
    t0 = time.time()
    meta = json.loads((REPO / "docs" / "data" / "map_meta.json").read_text())
    ox, oy = meta["origin_x"], meta["origin_y"]

    prov_raw = json.loads((OUT / "province.json").read_text())
    province = unary_union([Polygon(p[0]) for p in prov_raw if p and len(p[0]) >= 4]).buffer(300)

    osm = json.loads((REPO / "data" / "osm" / "alberta_osm_highways.json").read_text())
    lines = []
    for e in osm["elements"]:
        if e.get("type") != "way" or e.get("tags", {}).get("highway") != "secondary":
            continue
        g = e.get("geometry")
        if not g or len(g) < 2:
            continue
        lines.append(LineString([(p["lon"], p["lat"]) for p in g]))
    print(f"{len(lines)} secondary ways, {time.time()-t0:.0f}s")

    gs = gpd.GeoSeries(lines, crs=4326).to_crs(3401).translate(xoff=-ox, yoff=-oy).simplify(SIMP)
    gs = gs[gs.intersects(province)].intersection(province)
    gs = gs[~gs.is_empty]

    out = []
    def emit(geom):
        if geom.geom_type == "LineString":
            c = list(geom.coords)
            if len(c) >= 2:
                out.append({"path": [[round(x, 1), round(y, 1)] for x, y in c]})
        elif geom.geom_type in ("MultiLineString", "GeometryCollection"):
            for sub in geom.geoms:
                emit(sub)
    for geom in gs:
        emit(geom)

    (OUT / "secondary.json").write_text(json.dumps(out, separators=(",", ":")))
    sz = (OUT / "secondary.json").stat().st_size
    verts = sum(len(d["path"]) for d in out)
    print(f"secondary.json: {len(out)} paths, {verts} verts, {sz/1e6:.2f}MB  {time.time()-t0:.0f}s")


if __name__ == "__main__":
    build_water()
    build_secondary()
